import crafttweaker.api.loot.modifier.CommonLootModifiers;

CommonLootModifiers.removeAll(
	// Galosphere
	<galosphere:silver_bomb>,
	// Immersive Engineering
	<immersiveengineering:armor_piercing>,
	<immersiveengineering:dragons_breath>,
	<immersiveengineering:firework>,
	<immersiveengineering:homing>,
	<immersiveengineering:potion>,
	<immersiveengineering:wolfpack>,
	<immersiveengineering:shield>,
	<immersiveengineering:shader_bag_common>,
	<immersiveengineering:shader_bag_uncommon>,
	<immersiveengineering:shader_bag_twilight>,
	<immersiveengineering:shader_bag_rare>,
	<immersiveengineering:shader_bag_epic>,
	<immersiveengineering:shader_bag_ie_masterwork>,
	// Infernal Espanscion
	<infernalexp:ascus_bomb>,
	// Leathered Boots
	<leatheredboots:leathered_chainmail_boots>,
	<leatheredboots:leathered_iron_boots>,
	<leatheredboots:leathered_gold_boots>,
	<leatheredboots:leathered_diamond_boots>,
	<leatheredboots:leathered_netherite_boots>,
	// Library Ferret
	<libraryferret:diamond_coins_jtl>,
	<libraryferret:emerald_coins_jtl>,
	<libraryferret:gold_coins_jtl>,
	<libraryferret:iron_coins_jtl>,
	<libraryferret:netherite_coins_jtl>,
	// Mekanism
	<mekanismtools:wood_paxel>,
	// Minecraft
	<minecraft:wooden_axe>,
	<minecraft:wooden_hoe>,
	<minecraft:wooden_sword>,
	<minecraft:wooden_shovel>,
	<minecraft:wooden_pickaxe>,
	// Pneumatic Craft
	<pneumaticcraft:amadron_tablet>,
	<pneumaticcraft:gun_ammo_ap>,
	<pneumaticcraft:gun_ammo_explosive>,
	<pneumaticcraft:gun_ammo_freezing>,
	<pneumaticcraft:gun_ammo_incendiary>,
	<pneumaticcraft:gun_ammo_weighted>,
	<pneumaticcraft:micromissiles>,
	<pneumaticcraft:vortex_cannon>,
	// Supplementaries
	<supplementaries:bomb>,
	<supplementaries:bomb_blue>,
	<supplementaries:bomb_spiky>,
	// Therminal Series
	<thermal:bronze_coin>,
	<thermal:constantan_coin>,
	<thermal:copper_coin>,
	<thermal:electrum_coin>,
	<thermal:enderium_coin>,
	<thermal:gold_coin>,
	<thermal:invar_coin>,
	<thermal:iron_coin>,
	<thermal:lead_coin>,
	<thermal:lumium_coin>,
	<thermal:netherite_coin>,
	<thermal:nickel_coin>,
	<thermal:rose_gold_coin>,
	<thermal:signalum_coin>,
	<thermal:silver_coin>,
	<thermal:steel_coin>,
	<thermal:tin_coin>,
	<thermal:earth_grenade>,
	<thermal:ender_grenade>,
	<thermal:explosive_grenade>,
	<thermal:fire_grenade>,
	<thermal:glowstone_grenade>,
	<thermal:ice_grenade>,
	<thermal:lightning_grenade>,
	<thermal:phyto_grenade>,
	<thermal:redstone_grenade>,
	<thermal:slime_grenade>,
	<thermal:earth_tnt>,
	<thermal:ender_tnt>,
	<thermal:fire_tnt>,
	<thermal:glowstone_tnt>,
	<thermal:ice_tnt>,
	<thermal:lightning_tnt>,
	<thermal:phyto_tnt>,
	<thermal:redstone_tnt>,
	<thermal:slime_tnt>,
	<thermal_extra:dragonsteel_coin>,
	<thermal_extra:shellite_coin>,
	<thermal_extra:soul_infused_coin>,
	<thermal_extra:twinite_coin>,
	<unusualend:void_totem>,
	// The One Probe
	<theoneprobe:creativeprobe>,
	<theoneprobe:diamond_helmet_probe>,
	<theoneprobe:gold_helmet_probe>,
	<theoneprobe:iron_helmet_probe>,
	<theoneprobe:probe>,
	<theoneprobe:probenote>
);
